name: Regression and Unit Testing

on:
  push:
    branches:
      - 'main'
      - 'feature_regressiontests'

  workflow_call:
    inputs:
      runner:
        description: 'The github runner to use'
        default: 'ubuntu-latest'
        required: false 
        type: string
jobs:
  build:
    name: build package
    strategy: 
      fail-fast: false
    runs-on: ${{ inputs.runner || 'ubuntu-latest' }}
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REPO_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64 
          file: ./docker/build/Dockerfile_test
          tags: | 
            ecbunschoten/su2dataminer_test:latest
            ecbunschoten/su2dataminer_test:1.0.0
      
      # - name: Push image to GHCR
      #   run: |
      #     docker buildx imagetools create \
      #       --tag ghcr.io/ecbunschoten/su2dataminer_test:latest \
      #       --tag ghcr.io/ecbunschoten/su2dataminer_test:1.0.0 \
      #       ecbunschoten/su2dataminer_test:latest

      # - name: Pre Cleanup
      #   uses: docker://ghcr.io/ecbunschoten/su2dataminer_test:latest
      #   with:
      #     entrypoint: /bin/rm
      #     args: -rf install install_bin.tgz src ccache
      
      - name: Build
        uses: docker://ghcr.io/ecbunschoten/su2dataminer_test:latest
        with:
          args: -b ${{ github.ref }}
      